name: minetest
title: Minetest
summary: Open source voxel game engine
description: |
  Minetest is a minecraft-inspired game written from scratch and licensed under the LGPL (version 2.1 or later). It supports both survival and creative modes along with multiplayer support, dynamic lighting, and an "infinite" map generator.

  **Authors**

  This snap package is maintained by the Snapcrafters community. It is not necessarily endorsed or officially supported by the developers of the application itself.
license: LGPL-2.1-or-later
website: https://www.minetest.net/
contact: https://github.com/snapcrafters/minetest/issues
issues: https://github.com/snapcrafters/minetest/issues
source-code: https://github.com/snapcrafters/minetest
icon: snap/gui/minetest.svg
adopt-info: minetest

base: core18
compression: lzo
grade: stable
confinement: strict
architectures:
  - build-on: armhf
  - build-on: i386
  - build-on: amd64

apps:
  minetest:
    environment:
      HOME: "$SNAP_USER_COMMON"
    command: launcher
    plugs: [desktop, desktop-legacy, x11, network, network-bind, opengl, pulseaudio, home, removable-media]

parts:
  launcher:
    source: scripts
    plugin: dump

  irrlicht:
    source: https://github.com/minetest/irrlicht.git
    plugin: cmake
    configflags:
      - -DBUILD_SHARED_LIBS=OFF
    build-packages:
      - libpng-dev
      - libjpeg-dev
      - libx11-dev
      - libxi-dev
      - libglu1-mesa-dev
      - zlib1g-dev
    prime:
      - -*

  minetestgame:
    source: https://github.com/minetest/minetest_game.git
    plugin: dump
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git for-each-ref --sort=taggerdate --format '%(tag)' refs/tags | tail -n 1)"
      last_released_tag="$(snap info minetest | awk '$1 == "latest/beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
    override-build: |
      snapcraftctl build
    organize:
      '*': 'share/minetest/games/minetest_game/'

  minetest:
    plugin: cmake
    source: https://github.com/minetest/minetest.git
    after: [ irrlicht ]
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git for-each-ref --sort=taggerdate --format '%(tag)' refs/tags | tail -n 1)"
      last_released_tag="$(snap info minetest | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        # Needed  by the cmake plugin
        cd ../src
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl set-version "$(git describe --tags)"
    override-build: |
      snapcraftctl build
    configflags: ["-DRUN_IN_PLACE=FALSE", "-DCMAKE_BUILD_TYPE=Release"]
    build-packages:
      - cmake
      - gcc
      - g++
      - gettext
      - imagemagick
      - libbz2-dev
      - libcurl4-gnutls-dev
      - libfreetype6-dev
      - libglu1-mesa-dev
      - libjpeg-dev
      - libjsoncpp-dev
      - libleveldb-dev
      - libluajit-5.1-dev
      - libogg-dev
      - libopenal-dev
      - libpng-dev
      - libpulse-dev
      - libsqlite3-dev
      - libvorbis-dev
      - libx11-dev
      - libzstd-dev
      - zlib1g-dev
    stage-packages:
      - libgl1-mesa-dri
      - libpulse0
      - libcurl3-gnutls
      - libgl1-mesa-glx
      - libxshmfence1
      - libxcb-sync1
      - libxcb-present0
      - libxcb-glx0
      - libxcb-dri3-0
      - libxcb-dri2-0
      - libvorbisfile3
      - libsnappy1v5
      - libopenal1
      - libluajit-5.1-2
      - libleveldb1v5
      - libjpeg-turbo8
      - libxxf86vm1
      - libxfixes3
      - libxext6
      - libxdamage1
      - libx11-6
      - libx11-xcb1
      - libzstd1
      - libfreetype6
      - libpng16-16
      - libjsoncpp1
      - libxi6
